# Generated by Django 5.0.1 on 2024-01-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_rename_name_category_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Product',
        ),
    ]
