# Generated by Django 5.0.1 on 2024-01-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_rename_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TitleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_word', models.CharField(choices=[('1', 'page'), ('2', 'word')], max_length=1)),
                ('number_page_word', models.IntegerField()),
                ('condition', models.CharField(choices=[('1', 'force'), ('2', 'normal')], max_length=1)),
                ('choice_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='translate.choice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='translate.product')),
                ('title_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='translate.titletype')),
            ],
        ),
    ]
