# Generated by Django 5.0.1 on 2024-01-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0004_choice_titletype_weblog_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%Y/%m/'),
        ),
    ]
