# Generated by Django 5.0.1 on 2024-01-13 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0005_alter_weblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='weblog/%Y/%m/'),
        ),
    ]
